"""The four GitHub Actions workflows.

Generated by `tools/gen-ci.py` for the same reason the installers are: the
packages become four repositories, so each needs a complete workflow, and the
three module ones should differ only in nothing.

Nothing here runs a workflow. These parse the YAML and assert the properties
that would otherwise be discovered by pushing and waiting — a red CI run is a
slow way to learn that a step name was misspelled.
"""

import importlib.util
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent.parent
PACKAGES = ROOT / "packages"
NAMES = ("core", "files", "dock", "apps")
MODULES = ("files", "dock", "apps")

try:
    import yaml
except ImportError:          # pragma: no cover - environment-dependent
    yaml = None

needs_yaml = unittest.skipUnless(yaml is not None, "PyYAML is not installed")


def workflow_path(name: str) -> Path:
    return PACKAGES / f"palisade-{name}" / ".github/workflows/test.yml"


def text(name: str) -> str:
    return workflow_path(name).read_text()


@needs_yaml
class ShapeTests(unittest.TestCase):
    def load(self, name):
        return yaml.safe_load(text(name))

    def steps(self, name):
        return self.load(name)["jobs"]["test"]["steps"]

    def test_every_package_has_one(self):
        for name in NAMES:
            with self.subTest(package=name):
                self.assertTrue(workflow_path(name).exists())

    def test_the_yaml_parses(self):
        for name in NAMES:
            with self.subTest(package=name):
                self.assertIsInstance(self.load(name), dict)

    def test_it_runs_on_the_pinned_runner(self):
        """`ubuntu-latest` moves under you. A GTK and PyGObject combination
        that works is worth pinning."""
        for name in NAMES:
            with self.subTest(package=name):
                self.assertEqual(self.load(name)["jobs"]["test"]["runs-on"],
                                 "ubuntu-24.04")

    def test_both_runs_are_present(self):
        """With a display and without. The second is not redundant: a test
        that builds a widget without a display segfaults rather than failing,
        so it has to be observed from outside the process."""
        for name in NAMES:
            with self.subTest(package=name):
                runs = [s.get("run", "") for s in self.steps(name)]
                self.assertTrue(any("xvfb-run -a python3 -m pytest" in r
                                    for r in runs))
                bare = [r for r in runs
                        if r.strip() == "python3 -m pytest tests -q"]
                self.assertEqual(len(bare), 1, runs)

    def test_the_headless_run_really_has_no_display(self):
        """Inheriting the runner's DISPLAY would make it a second copy of the
        first run — which is exactly how this went unnoticed locally."""
        for name in NAMES:
            with self.subTest(package=name):
                step = next(s for s in self.steps(name)
                            if s.get("run", "").strip()
                            == "python3 -m pytest tests -q")
                self.assertEqual(step["env"]["DISPLAY"], "")
                self.assertEqual(step["env"]["WAYLAND_DISPLAY"], "")


@needs_yaml
class CoreDependencyTests(unittest.TestCase):
    def steps(self, name):
        return yaml.safe_load(text(name))["jobs"]["test"]["steps"]

    def test_modules_check_core_out_rather_than_installing_it(self):
        """A module's CI should fail when *this* change breaks against core's
        main, not against whatever was last released."""
        for name in MODULES:
            with self.subTest(package=name):
                step = next(s for s in self.steps(name)
                            if s.get("name") == "Fetch palisade-core")
                self.assertEqual(step["with"]["path"], ".core")
                self.assertIn("github.repository_owner",
                              step["with"]["repository"])

    def test_the_owner_is_the_repository_s_own(self):
        """Not PALISADE_OWNER. A fork's CI should test the fork's core, and
        hard-coding an owner would send every fork to the upstream one."""
        for name in MODULES:
            with self.subTest(package=name):
                self.assertNotIn("PALISADE_OWNER", text(name))

    def test_core_fetches_nothing(self):
        """It is the dependency."""
        names = [s.get("name") for s in self.steps("core")]
        self.assertNotIn("Fetch palisade-core", names)

    def test_modules_put_the_checkout_on_pythonpath(self):
        for name in MODULES:
            with self.subTest(package=name):
                for step in self.steps(name):
                    if "pytest" in step.get("run", ""):
                        self.assertIn(".core/src", step["env"]["PYTHONPATH"])

    def test_the_expansion_is_not_double_escaped(self):
        """`${{{{ ... }}}}` is what a format string produces when a value is
        escaped as though it were a template. It reaches Actions as literal
        braces and the checkout silently targets a repository called
        "${{ github.repository_owner }}". Caught by reading the output."""
        for name in NAMES:
            with self.subTest(package=name):
                self.assertNotIn("${{{{", text(name))
                self.assertNotIn("}}}}", text(name))


class DependencyTests(unittest.TestCase):
    def test_the_optional_libraries_are_installed_in_ci(self):
        """CI is the one place that should exercise the paths a developer
        machine may not have — GtkSourceView has never run locally."""
        for name in NAMES:
            with self.subTest(package=name):
                self.assertIn("gir1.2-gtksource-5", text(name))
                self.assertIn("gir1.2-poppler-0.18", text(name))

    def test_layer_shell_is_built_from_a_pinned_tag(self):
        """It is not packaged for 24.04. Tracking main would let an unrelated
        library turn a red build into an afternoon."""
        for name in NAMES:
            with self.subTest(package=name):
                self.assertIn("--branch v", text(name))
                self.assertNotIn("--branch main", text(name))


class SyncTests(unittest.TestCase):
    def test_the_workflows_match_the_template(self):
        """Rendered in memory, not by running the generator: a test that
        regenerates repairs what it is checking."""
        spec = importlib.util.spec_from_file_location(
            "gen_ci", ROOT / "tools/gen-ci.py")
        gen = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(gen)
        for name in NAMES:
            fields = gen.MODULES[name]
            if name != "core":
                fields = {**gen.MODULE_DEFAULTS, **fields}
            with self.subTest(package=name):
                self.assertEqual(
                    gen.TEMPLATE.format(
                        layer_shell=gen.LAYER_SHELL_VERSION,
                        core_step=fields["core_step"],
                        env=fields["env"],
                        env_extra=fields["env_extra"],
                    ),
                    text(name),
                    "out of sync: edit tools/gen-ci.py and rerun it")

    def test_every_package_has_a_contributing_guide(self):
        for name in NAMES:
            with self.subTest(package=name):
                guide = PACKAGES / f"palisade-{name}" / "CONTRIBUTING.md"
                self.assertTrue(guide.exists())
                self.assertIn("one `./install.sh`", guide.read_text())


if __name__ == "__main__":
    unittest.main()
