#!/usr/bin/env python3
"""Write each package's GitHub Actions workflow from one template.

The four packages become four repositories, so each needs a complete workflow
of its own — a shared one is not an option once they are split. Generating
them keeps the three module workflows identical where they should be, which is
everywhere except the package name.

Run after changing the template:

    python3 tools/gen-ci.py

Core's differs in one way that matters: it is the dependency, so it has
nothing to check out first. The modules fetch it into `.core` and put it on
PYTHONPATH rather than pip-installing it, because a module's CI should fail
when *this* change breaks against core's main, not against whatever was last
released.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# gtk4-layer-shell is not packaged for Ubuntu 24.04 and there is no PPA worth
# trusting, so it is built. Pinned rather than tracking main: a compositor
# protocol library changing under CI turns an unrelated red build into an
# afternoon. v1.1.1 is the oldest release that works with the GTK 4.14 in
# 24.04, so it is also the floor this project supports.
LAYER_SHELL_VERSION = "v1.1.1"

TEMPLATE = """\
# Generated by tools/gen-ci.py — edit the template, not this file.
name: tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      # PyGObject and GTK are system libraries, not wheels. poppler and
      # gtksourceview are optional at runtime and installed here on purpose:
      # CI is the one place that should exercise the paths a developer
      # machine may not have. xvfb because a few tests build a real widget,
      # and constructing one without a display segfaults rather than failing.
      - name: System dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \\
            python3-gi python3-gi-cairo gir1.2-gtk-4.0 \\
            gir1.2-gtksource-5 gir1.2-poppler-0.18 \\
            xvfb libgtk-4-dev meson ninja-build valac \\
            gobject-introspection libgirepository1.0-dev

      # Not packaged for 24.04. Pinned rather than tracking main so a change
      # in a compositor protocol library cannot turn an unrelated build red.
      - name: Build gtk4-layer-shell {layer_shell}
        run: |
          git clone --depth 1 --branch {layer_shell} \\
            https://github.com/wmww/gtk4-layer-shell .layer-shell
          cd .layer-shell
          meson setup --prefix /usr build -Dexamples=false -Ddocs=false -Dtests=false
          ninja -C build
          sudo ninja -C build install
          sudo ldconfig
{core_step}
      - name: Tests
        run: xvfb-run -a python3 -m pytest tests -q
{env}
      # The suite must also survive having no display at all: a test that
      # builds a widget without one segfaults, taking every result with it.
      # `tests/test_headless.py` asserts this from the inside; this runs it
      # from the outside, where an exit code is the whole answer.
      - name: Tests without a display
        run: python3 -m pytest tests -q
        env:
          DISPLAY: ""
          WAYLAND_DISPLAY: ""
{env_extra}
"""

CORE_STEP = """
      # Core is the dependency, so the module is tested against core's *main*
      # rather than whatever was last released — a module change that breaks
      # against current core should fail here, not after a release.
      - name: Fetch palisade-core
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/palisade-core
          path: .core
"""

MODULE_ENV = """        env:
          PYTHONPATH: ${{ github.workspace }}/.core/src
"""

MODULE_ENV_EXTRA = """          PYTHONPATH: ${{ github.workspace }}/.core/src
"""

CONTRIBUTING = """\
# Contributing to {package}

## Running it

{package} is part of [Palisade](https://github.com/PALISADE_OWNER/palisade-core).
{context}

```bash
./install.sh
```

Running the installer from a clone installs from that clone, so a change is
one `./install.sh` away from being on screen.

## Running the tests

From this directory:

```bash
xvfb-run -a python3 -m pytest tests -q
```

`xvfb-run` is only needed for the handful of tests that build a real GTK
widget. Everything else is deliberately display-free, and both runs are
checked in CI — including the one with no display at all, because
constructing a widget without a display does not raise, it **segfaults**, and
takes every result collected so far with it. A test that needs a display goes
behind `@needs_display` from `tests/_display.py`.

{pythonpath}

## What a change should carry

- **One concern per commit**, with a message that says *why* rather than
  what. The diff already says what.
- **A test that would have caught the bug.** Not a test that passes — a test
  that fails before the fix. Reintroduce the bug and watch it go red; if it
  does not, the test is checking something else.
- **No claim in the docs that the code does not do.** If something is written
  and unverified, say so where a reader will find it.

## Boundaries that are not negotiable

- Modules import `palisade` only. A module importing another module means
  uninstalling one breaks the others, and the four packages stop being four
  packages.
- Core imports no module. It discovers them through entry points; installation
  *is* registration.
- Anything that reaches a shell or an interpolated string is validated at the
  boundary, even when the value came from the compositor. See `SECURITY.md`.

## Reporting something

Issues on this repository. For anything touching panel drawing, layer-shell
behaviour or the config format, open it against `palisade-core` instead —
that is where the code lives.
"""

MODULES = {
    "core": dict(
        package="palisade-core",
        core_step="",
        env="",
        env_extra="",
        context=(
            "It is the panel itself: everything else is a module that plugs "
            "into it.\n\nTo work on it from a clone:"
        ),
        pythonpath=(
            "Core has no dependency on the modules. `PALISADE_MODULES` is the "
            "dev\noverride that loads them from a working tree; see "
            "`src/palisade/registry.py`."
        ),
    ),
    "files": dict(package="palisade-files"),
    "dock": dict(package="palisade-dock"),
    "apps": dict(package="palisade-apps"),
}

MODULE_DEFAULTS = dict(
    core_step=CORE_STEP,
    env=MODULE_ENV,
    env_extra=MODULE_ENV_EXTRA,
    context=(
        "It is a module: it needs\n[palisade-core]"
        "(https://github.com/PALISADE_OWNER/palisade-core) installed, and the\n"
        "installer fetches core for you if it is missing.\n\nFrom a clone:"
    ),
    pythonpath=(
        "Against a core checkout rather than an installed core, point\n"
        "`PYTHONPATH` at it:\n\n```bash\n"
        "PYTHONPATH=../palisade-core/src xvfb-run -a python3 -m pytest tests -q\n"
        "```\n\nThat is what CI does."
    ),
)


def main() -> int:
    for name, fields in MODULES.items():
        if name != "core":
            fields = {**MODULE_DEFAULTS, **fields}
        pkg = ROOT / "packages" / f"palisade-{name}"

        workflow = pkg / ".github" / "workflows" / "test.yml"
        workflow.parent.mkdir(parents=True, exist_ok=True)
        workflow.write_text(
            TEMPLATE.format(
                layer_shell=LAYER_SHELL_VERSION,
                core_step=fields["core_step"],
                env=fields["env"],
                env_extra=fields["env_extra"],
            ),
            encoding="utf-8",
        )
        print(f"wrote {workflow.relative_to(ROOT)}")

        contributing = pkg / "CONTRIBUTING.md"
        contributing.write_text(
            CONTRIBUTING.format(
                package=fields["package"],
                context=fields["context"],
                pythonpath=fields["pythonpath"],
            ),
            encoding="utf-8",
        )
        print(f"wrote {contributing.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
